// Knowledge Multiverse — Automated Security & Proctor Incident Notifier
// Powered by Kapil
// Dispatches immediate alerts to kapilnarula27july@gmail.com and namaste@sarlayash.com

const PRIMARY_ALERT_EMAIL = 'kapilnarula27july@gmail.com';
const SECONDARY_ALERT_EMAIL = 'namaste@sarlayash.com';

export async function sendCheatingIncidentReport({
  incidentId,
  learnerName,
  persona,
  violationReason,
  timeSpent,
  lockedUntil
}) {
  const timestamp = new Date().toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'long',
    timeZone: 'Asia/Kolkata'
  });

  const unlockTime = new Date(lockedUntil).toLocaleString('en-US', {
    dateStyle: 'full',
    timeStyle: 'long',
    timeZone: 'Asia/Kolkata'
  });

  const payload = {
    _subject: `🚨 ACADEMIC INTEGRITY VIOLATION: ${learnerName || 'Learner'} (Hard Mock 100)`,
    _cc: SECONDARY_ALERT_EMAIL,
    _replyto: PRIMARY_ALERT_EMAIL,
    _template: 'table',
    'Incident ID': incidentId,
    'Learner Name': learnerName || 'Anonymous Learner',
    'Track / Persona': persona ? persona.toUpperCase() : 'GENERAL',
    'Assessment': 'FAANG Hard Mock Assessment (100 MCQs - 2 Hours)',
    'Violation Detected': violationReason,
    'Infraction Time (IST)': timestamp,
    'Elapsed Exam Time': timeSpent || 'Under 5 minutes',
    'Penalty Enforced': 'Exam Cancelled (0% Score) & Login Locked for 24 Hours',
    'Account Locked Until': unlockTime,
    'Client User Agent': typeof navigator !== 'undefined' ? navigator.userAgent : 'Unknown',
    'Screen Resolution': typeof window !== 'undefined' ? `${window.screen?.width}x${window.screen?.height}` : 'Unknown',
    'Security Notice': 'Automated report generated by Knowledge Multiverse Anti-Cheat Sentinel.'
  };

  // 1. Archive incident locally in audit log
  try {
    const existing = JSON.parse(localStorage.getItem('km_security_incidents') || '[]');
    existing.unshift({ ...payload, loggedAt: Date.now() });
    localStorage.setItem('km_security_incidents', JSON.stringify(existing.slice(0, 50)));
  } catch (e) {
    console.error('Failed to log security incident locally:', e);
  }

  // 2. Dispatch HTTP alert to FormSubmit automated email gateway
  try {
    const response = await fetch(`https://formsubmit.co/ajax/${PRIMARY_ALERT_EMAIL}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify(payload)
    });
    const result = await response.json();
    return { success: true, result };
  } catch (err) {
    console.warn('Network email trigger warning (fallback queued):', err);
    return { success: false, error: err.message };
  }
}

// Generate pre-formatted mailto URL for immediate manual email verification fallback
export function getMailtoSecurityReport({
  incidentId,
  learnerName,
  violationReason,
  lockedUntil
}) {
  const subject = encodeURIComponent(`🚨 CHEATING INCIDENT REPORT: ${learnerName || 'Learner'} [${incidentId}]`);
  const body = encodeURIComponent(`=======================================================
ACADEMIC INTEGRITY VIOLATION INCIDENT REPORT
Knowledge Multiverse — FAANG Hard Mock Examination
=======================================================

Incident ID: ${incidentId}
Learner: ${learnerName || 'Learner'}
Violation: ${violationReason}
Time: ${new Date().toLocaleString()}
Penalty: Disqualified (0% Score) & Login Locked for 24 Hours
Locked Until: ${new Date(lockedUntil).toLocaleString()}

Target Notification:
Primary: ${PRIMARY_ALERT_EMAIL}
Secondary: ${SECONDARY_ALERT_EMAIL}

Client Telemetry:
${typeof navigator !== 'undefined' ? navigator.userAgent : 'N/A'}
Screen: ${typeof window !== 'undefined' ? `${window.screen?.width}x${window.screen?.height}` : 'N/A'}
=======================================================`);

  return `mailto:${PRIMARY_ALERT_EMAIL}?cc=${SECONDARY_ALERT_EMAIL}&subject=${subject}&body=${body}`;
}
